[phases.setup]
nixLibs = ["zlib", "libuuid", "libxcb", "xorg.libX11", "xorg.libXrender", "xorg.libXext"]
nixPkgs = ["nodejs", "chromium", "xorg.libxshmfence", "glib", "nss", "nspr", "atk", "at-spi2-atk", "xorg.libXt", "libdrm", "mesa", "cairo", "pango"]
aptPkgs = ["libgbm-dev", "libxkbcommon-dev", "libnss3", "libatk1.0-0", "libatk-bridge2.0-0", "libcups2", "libxcomposite1", "libxdamage1", "libxfixes3", "libxrandr2", "libpango-1.0-0", "libcairo2"]

[phases.install]
cmds = ["pip install -r requirements.txt", "playwright install chromium"]

[variables]
PLAYWRIGHT_BROWSERS_PATH = "/workspace/playwright-browsers"