[phases.setup]
nixPkgs = ["nodejs", "chromium", "playwright-driver", "xvfb-run", "libgbm", "libdrm", "libxkbcommon", "libxshmfence", "mesa"]

[phases.install]
cmds = ["pip install -r requirements.txt", "playwright install"]

[start]
cmd = "python main.py"